## DATA SCIENCE AND ANALYTICS IN A "PANDEMIC"

## Script Generated by: Dennis Mathaisel | Abdullah Zahid
## Data Source: https://ourworldindata.org/coronavirus

## This script entails a total of 6 visualizations 
## which was not referenced within the paper
## but contributed to the creation of the paper. 

## Packages Utilized
install.packages("ggvis", dep=TRUE)
install.packages("lattice", dep=TRUE)
install.packages("RJSplot", dep=TRUE)
install.packages("hrbrthemes")
install.packages("Hmisc")
install.packages("RJSplot")

library(ggvis)
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
library(tidyr)
library(Hmisc)
library(RJSplot)




###############################
###############################
# THIS IS START OF THE SCRIPT #
###############################
###############################

#Read File: The file is provided within the "Data" section of the repository
covid<- read.csv("C:/Users/dchae2/Desktop/Repository/Data/owid-covid-data.csv")
covid<- read.csv(file.choose())

#Check internal structure and summary statistics of the "covid" dataset
str(covid)
summary (covid)

#Data Frame verification of the "covid" dataset
is.data.frame(covid)

#Checking for Attributes of the "covid" dataframe
names(covid)
dim(covid)
class(covid)
length(covid)
attributes(covid)

#Alteration of the variable "date" to the correct format
covid$date <- as.Date(covid$date, format = "%m/%d/%Y")
str(covid)

#"topcovid": Filtered Dataset containing the 10 Countries with the Highest COVID-19 Confirmed Cases
for (i in 1:nrow(covid))
{
  covid$Record[i]=i
  topcovid = select(covid,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths)%>%
    filter(iso_code %in% c("BRA", "FRA", "DEU", "IND", "ITA","RUS","ESP","TUR","GBR","USA"))
}
topcovid
str(topcovid)

#Checking for Missing Values wihtin the "topcovid" dataset
anyNA(topcovid$iso_code)
anyNA(topcovid$location)
anyNA(topcovid$date)
anyNA(topcovid$total_cases)
anyNA(topcovid$new_cases)
anyNA(topcovid$total_deaths)
anyNA(topcovid$new_deaths)

#Removing Missing Values within the "topcovid" dataset
na.omit(topcovid$iso_code)
na.omit(topcovid$location)
na.omit(topcovid$date)
na.omit(topcovid$total_cases)
na.omit(topcovid$new_cases)
na.omit(topcovid$total_deaths)
na.omit(topcovid$new_deaths)



#######################################################                                   
#Graph 1                                              #
#Line graphs of the total confirmed cases of COVID-19 #
#in the Top 10 Confirmed Cases countries since:       # 
#######################################################

#1-1. OCTOBER

  #"October": filtered from "topcovid" containing only the rows that entail information since October
  for (i in 1:nrow(topcovid))
  {
    topcovid$Record[i]=i
    October = select(topcovid,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths)%>%
      filter(date > as.Date("2020-09-30"))
  }

October %>%
  ggplot( aes(x=date, y=total_cases, group=location, color=location)) +
  geom_line() +
  ggtitle("Cases of Covid Since October") +
  theme_ipsum() +
  ylab("Cases")



#1-2. NOVEMBER

  #"November": filtered from "topcovid" containing only the rows that entail information since November
  for (i in 1:nrow(topcovid))
  {
    topcovid$Record[i]=i
    November = select(topcovid,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths)%>%
      filter(date > as.Date("2020-10-31"))
  }

November %>%
  ggplot( aes(x=date, y=total_cases, group=location, color=location)) +
  geom_line() +
  ggtitle("Cases of Covid Since November") +
  theme_ipsum() +
  ylab("Cases")



#1-3. DECEMBER
  #"December": filtered from "topcovid" containing only the rows that entail information since December
  for (i in 1:nrow(topcovid))
  {
    topcovid$Record[i]=i
    December = select(topcovid,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths)%>%
      filter(date > as.Date("2020-11-30"))
  }

December %>%
  ggplot( aes(x=date, y=total_cases, group=location, color=location)) +
  geom_line() +
  ggtitle("Cases of Covid Since December") +
  theme_ipsum() +
  ylab("Cases")




#######################################################  
#Graph 2                                              #
#Bar Chart of the ratio between total confirmed cases #
#versus the death cases as of 2021.1.5                #
#######################################################

  #"covidGraph2": Subset from "topcovid" with observations pertaining to Top 10 confirmed cases countries until 2021.1.5
  covidGraph2 <- subset(topcovid, date=="2021-01-05" & (iso_code== "BRA"|iso_code== "FRA"|iso_code== "DEU"|iso_code==  "IND"|iso_code==  "ITA"|iso_code== "RUS"|iso_code== "ESP"|iso_code== "TUR"|iso_code== "GBR"|iso_code== "USA"), 
                        select=c(date, location, total_cases, total_deaths))
  
  #"testedPos": Subset from "covidGraph2" with "Alive + Tested Positive" Cases
  testedPos <- covidGraph2$total_cases - covidGraph2$total_deaths
  
  #"data": containing information on "Alive & Tested Positive" and Death for Top 10 Confirmed Cases Countries
  country <- rep(covidGraph2$location, each=2)
  caseType <- rep(c("Alive & Tested Positive", "Deaths"), 5)
  totalCases <- c(rbind(testedPos, covidGraph2$total_deaths))
  data <- data.frame(country, caseType, totalCases)

#2-1. Bar Chart of Death vs. Alive+Tested Positive Cases for Top 10 countries
ggplot(data, aes(fill=caseType, y=totalCases, x=country)) + geom_bar(position="fill", stat="identity") +
ggtitle("Cases:Death ratio")




#######################################################  
#Graph 3                                              #
#Barplot of Confirmed Cases per Million of Population #
#in the Top 10 Countries as of 2021.1.5               #
#######################################################

  #Calculations Cases per million population 
  #(cases/(population/100000))
    #Brazil
    round(7961673/(209500000/1000000),digits=2)
    #Spain
    round(2024904/(46940000/1000000),digits=2)
    #Italy 
    round(2220361/(60000000/1000000),digits=2)
    #Germany
    round(1886561/(84000000/1000000),digits=2)
    #United States
    round(21574043/(331000000/1000000),digits=2)
    #India
    round(10413417/(1353000000/1000000),digits=2)
    #France
    round(2763370/(66990000/1000000),digits=2)
    #Turkey
    round(2296102/(82000000/1000000),digits=2)
    #United Kingdom
    round(2898052/(66650000/1000000),digits=2)
    #Russia
    round(3297833/(144500000/1000000),digits=2)

#3-1. Barplot containing information on the confirmed cases per million population (Top 10 Confirmed Cases Countries)
barplot1 <- data.frame(
  Country=c("Brazil","Spain","Italy","Germany","USA","India","France","Turkey","United Kingdom","Russia"),
  Cases=c(38003.21,43138.13,37006.02,22459.06,65178.38,7696.54,41250.49,28001.24,43481.65,22822.37)
)

  ggplot(barplot1, aes(x=reorder(Country, Cases), y=Cases, label=Cases)) +
  geom_bar(aes(fill=Country), stat= "identity") +
  coord_flip() +
  geom_text(size=4) +
  ylab("Cases per million population") +
  xlab("Location") +
  ggtitle("Cases per Million Population for Top 10 Countries")



#######################################################  
#Graph 4                                              #
#Scatterplot of Confirmed Cases vs. Death Cases       #
#in the Top 10 Countries as of 2021.1.5               #
#######################################################

#4-1. Scatterplot of Confirmed Cases vs. Death Cases in Top 10 Countries
topcovid %>% ggvis(~total_cases, ~total_deaths) %>% layer_points(fill = ~factor(location))


