## DATA SCIENCE AND ANALYTICS IN A "PANDEMIC"

## Script Generated by: Dennis Mathaisel
## Data Source: cached from Rami Krispin's coronavirus package


## This script entails the data structure visualization 
## referenced as Figure 1 in the publication.


#Packages Utilized
install.packages("readr")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("DataExplorer")
library(DataExplorer)
library(readr)
library(dplyr)
library(ggplot2)



###############################
###############################
# THIS IS START OF THE SCRIPT #
###############################
###############################

#Loading the dataset from Rami Krispin's github sourcing the coronavirus package
urlfile="https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv"
covid_tab<-read_csv(url(urlfile))

#1. Visualization Demonstrating the Data Structure of dataframe "covid_tab"
plot_str(covid_tab)

#Checking the Internal Structure and first 5 rows of the observations from "covid_tab"
str(covid_tab)
head(covid_tab)

#Analyzing the number of observations for: confirmed, Death and Recovered
table(covid_tab$type)

#Altering the date varaible in the m.d.Y format
covid_tab$date <- as.date(covid_tab$date, format = "%m/%d/%Y")



#2. Barplot demonstrating global confirmed cases in a global scale
covid_tab %>% filter(type == 'confirmed')%>% 
  group_by(date) %>% 
  summarise(cases = sum(cases))%>% 
  ggplot(aes(x = date, y = cases))+ geom_bar(stat = 'identity')+   
  theme(axis.text.x = element_text(angle = 45))

#3. Barplot demonstrating global death cases in a global scale
covid_tab %>%
  filter(type == 'death')%>%
  group_by(date)%>% 
  summarise(death = sum(cases))%>% ggplot(aes(x = date, y =
                                                 death))+ 
  geom_bar(stat = 'identity')+ theme(axis.text.x = element_text(angle
                                                                = 45))

#4. Barplot demonstrating death vs. recovered in a global scale
covid_tab %>%
  filter(!grepl('confirmed', type)) %>%
  group_by(date, type) %>%
  summarise(cases = sum(cases))%>%
  ggplot(aes(x = date, y = cases, fill = type))+
  geom_bar(stat = 'identity')+
  theme(axis.text.x = element_text(angle = 45))

#5. Barplot demonstrating death vs. recovered vs. confirmed in a global scale
covid_tab %>%
#  filter(!grepl('confirmed', type))%>%
  group_by(date, type)%>%
  summarise(cases = sum(cases))%>%
  ggplot(aes(x = date, y = cases, fill = type))+
  geom_bar(stat = 'identity', position = 'dodge')+
  theme(axis.text.x = element_text(angle = 45))


# Country
country_totals <- covid_tab %>%
  group_by(country) %>%
  summarise(max_cases = max(cases)) %>%
  left_join(country_totals, by = 'country') %>%
#  filter(grepl('confirmed', type) & max_cases >= 1000) %>% 
  group_by(date, type, country) %>%
  summarise(cases = sum(cases)) %>%
  ggplot(aes(x = date, y = cases, fill = country))+
  geom_bar(stat = 'identity')+
  theme(axis.text.x = element_text(angle = 45))

# Country
country_totals <- covid_tab %>%
  group_by(country) %>%
  left_join(country_totals, by = 'country') %>%
  filter(grepl('confirmed', type) & max_cases >= 1000) %>% 
  group_by(date, type, country) %>%
  summarise(cases = sum(cases)) %>%
  ggplot(aes(x = date, y = cases, fill = country))+
  geom_bar(stat = 'identity')+
  theme(axis.text.x = element_text(angle = 45))
