## DATA SCIENCE AND ANALYTICS IN A "PANDEMIC"

## Script Generated by: Abdullah Zahid
## Data Source: 

## This script entails a violin graph that was referenced in the publication 
## referenced as Figure 4.

#Packages Utilized
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
library(Hmisc)
library(tidyr)
library(ggvis)
library(plotly)


###############################
###############################
# THIS IS START OF THE SCRIPT #
###############################
###############################

#Read File: The file is provided within the "Data" section of the repository
covid= read.csv("D:/Project Files/COVID-19 and Usage of Data Science/Repository/Data/Figure 4. data/Asia Top 5 Cases.csv")

#Check internal structure and summary statistics of the "covid" dataset
str(covid)
summary(covid)

#Checking for Missing Values wihtin the "covid" dataset
anyNA(covid$date)
anyNA(covid$day)
anyNA(covid$month)
anyNA(covid$cases)
anyNA(covid$deaths)
anyNA(covid$countries)
anyNA(covid$geoId)
anyNA(covid$countrycode)
anyNA(covid$popData2018)
anyNA(covid$continent)


#1. Violin Graph entailing information on Number of Confirmed Cases in: 
  #China, India, Iran, Israel, Turkey
df <- covid

fig <- df %>%
  plot_ly(
    x = ~countries,
    y = ~cases,
    split = ~countries,
    type = 'violin',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    )
  ) 

fig <- fig %>%
  layout(
    xaxis = list(
      title = "Asia COVID Cases"
    ),
    yaxis = list(
      title = "Number of Cases",
      zeroline = F
    )
  )

fig
